language: python
install:
  - pip install -r requirements.txt
before_script:
  - python manage.py migrate
script:
  - test polls
  - coverage run --source='.' manage.py test polls
  - coverage report
after_success:
  - coveralls
